// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: node.proto

package node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Request_FullMethodName        = "/node.Node/request"
	Node_Request2PC_FullMethodName     = "/node.Node/Request2PC"
	Node_Accept_FullMethodName         = "/node.Node/accept"
	Node_Prepare2PC_FullMethodName     = "/node.Node/Prepare2PC"
	Node_Accept2PC_FullMethodName      = "/node.Node/Accept2PC"
	Node_Commit2PC_FullMethodName      = "/node.Node/Commit2PC"
	Node_Abort2PC_FullMethodName       = "/node.Node/Abort2PC"
	Node_CommitPhase2PC_FullMethodName = "/node.Node/CommitPhase2PC"
	Node_Commit_FullMethodName         = "/node.Node/commit"
	Node_Prepare_FullMethodName        = "/node.Node/prepare"
	Node_Heartbeat_FullMethodName      = "/node.Node/heartbeat"
	Node_NewView_FullMethodName        = "/node.Node/NewView"
	Node_SetNodeState_FullMethodName   = "/node.Node/SetNodeState"
	Node_PrintLog_FullMethodName       = "/node.Node/PrintLog"
	Node_PrintDB_FullMethodName        = "/node.Node/PrintDB"
	Node_PrintStatus_FullMethodName    = "/node.Node/PrintStatus"
	Node_PrintView_FullMethodName      = "/node.Node/PrintView"
	Node_GetViewEntries_FullMethodName = "/node.Node/GetViewEntries"
	Node_GetLogs_FullMethodName        = "/node.Node/GetLogs"
	Node_GetTxnStatus_FullMethodName   = "/node.Node/GetTxnStatus"
	Node_GetDB_FullMethodName          = "/node.Node/GetDB"
	Node_SetBalance_FullMethodName     = "/node.Node/SetBalance"
	Node_GetBalance_FullMethodName     = "/node.Node/GetBalance"
	Node_Checkpoint_FullMethodName     = "/node.Node/Checkpoint"
	Node_ResetDB_FullMethodName        = "/node.Node/ResetDB"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	Request(ctx context.Context, in *TxnMessage, opts ...grpc.CallOption) (*Reply, error)
	Request2PC(ctx context.Context, in *TxnMessage, opts ...grpc.CallOption) (*Reply, error)
	Accept(ctx context.Context, in *AcceptMsg, opts ...grpc.CallOption) (*AcceptedMsg, error)
	// 2PC-specific RPCs (separate from intra-shard Multi-Paxos)
	Prepare2PC(ctx context.Context, in *Prepare2PCReq, opts ...grpc.CallOption) (*Prepare2PCResp, error)
	Accept2PC(ctx context.Context, in *Accept2PCMsg, opts ...grpc.CallOption) (*Accept2PCResp, error)
	Commit2PC(ctx context.Context, in *Commit2PCMsg, opts ...grpc.CallOption) (*Acknowledgement, error)
	Abort2PC(ctx context.Context, in *Abort2PCMsg, opts ...grpc.CallOption) (*Acknowledgement, error)
	CommitPhase2PC(ctx context.Context, in *CommitPhase2PCReq, opts ...grpc.CallOption) (*CommitPhase2PCResp, error)
	// rpc accepted(AcceptedReq) returns (Acknowledgement);
	Commit(ctx context.Context, in *CommitReq, opts ...grpc.CallOption) (*Acknowledgement, error)
	// rpc reply(ReplyReq) returns (Acknowledgement);
	Prepare(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PromiseMsg, error)
	Heartbeat(ctx context.Context, in *HeartbeatMsg, opts ...grpc.CallOption) (*Acknowledgement, error)
	NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewReply, error)
	SetNodeState(ctx context.Context, in *NodeStateRequest, opts ...grpc.CallOption) (*NodeStateReply, error)
	PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error)
	PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBResponse, error)
	PrintStatus(ctx context.Context, in *PrintStatusRequest, opts ...grpc.CallOption) (*PrintStatusResponse, error)
	PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewResponse, error)
	GetViewEntries(ctx context.Context, in *GetViewEntriesReq, opts ...grpc.CallOption) (*GetViewEntriesResp, error)
	GetLogs(ctx context.Context, in *GetLogsReq, opts ...grpc.CallOption) (*GetLogsResp, error)
	GetTxnStatus(ctx context.Context, in *GetTxnStatusReq, opts ...grpc.CallOption) (*GetTxnStatusResp, error)
	GetDB(ctx context.Context, in *GetDBReq, opts ...grpc.CallOption) (*GetDBResp, error)
	// Migration support: set explicit balances on a node (used during resharding).
	SetBalance(ctx context.Context, in *SetBalanceReq, opts ...grpc.CallOption) (*SetBalanceResp, error)
	GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error)
	Checkpoint(ctx context.Context, in *CheckpointMsg, opts ...grpc.CallOption) (*Acknowledgement, error)
	ResetDB(ctx context.Context, in *ResetDBReq, opts ...grpc.CallOption) (*ResetDBResp, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Request(ctx context.Context, in *TxnMessage, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Node_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Request2PC(ctx context.Context, in *TxnMessage, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Node_Request2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Accept(ctx context.Context, in *AcceptMsg, opts ...grpc.CallOption) (*AcceptedMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptedMsg)
	err := c.cc.Invoke(ctx, Node_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Prepare2PC(ctx context.Context, in *Prepare2PCReq, opts ...grpc.CallOption) (*Prepare2PCResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prepare2PCResp)
	err := c.cc.Invoke(ctx, Node_Prepare2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Accept2PC(ctx context.Context, in *Accept2PCMsg, opts ...grpc.CallOption) (*Accept2PCResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Accept2PCResp)
	err := c.cc.Invoke(ctx, Node_Accept2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Commit2PC(ctx context.Context, in *Commit2PCMsg, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, Node_Commit2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Abort2PC(ctx context.Context, in *Abort2PCMsg, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, Node_Abort2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) CommitPhase2PC(ctx context.Context, in *CommitPhase2PCReq, opts ...grpc.CallOption) (*CommitPhase2PCResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPhase2PCResp)
	err := c.cc.Invoke(ctx, Node_CommitPhase2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Commit(ctx context.Context, in *CommitReq, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, Node_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Prepare(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PromiseMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseMsg)
	err := c.cc.Invoke(ctx, Node_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Heartbeat(ctx context.Context, in *HeartbeatMsg, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, Node_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewViewReply)
	err := c.cc.Invoke(ctx, Node_NewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SetNodeState(ctx context.Context, in *NodeStateRequest, opts ...grpc.CallOption) (*NodeStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStateReply)
	err := c.cc.Invoke(ctx, Node_SetNodeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintLogResponse)
	err := c.cc.Invoke(ctx, Node_PrintLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintDBResponse)
	err := c.cc.Invoke(ctx, Node_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) PrintStatus(ctx context.Context, in *PrintStatusRequest, opts ...grpc.CallOption) (*PrintStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintStatusResponse)
	err := c.cc.Invoke(ctx, Node_PrintStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintViewResponse)
	err := c.cc.Invoke(ctx, Node_PrintView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetViewEntries(ctx context.Context, in *GetViewEntriesReq, opts ...grpc.CallOption) (*GetViewEntriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetViewEntriesResp)
	err := c.cc.Invoke(ctx, Node_GetViewEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetLogs(ctx context.Context, in *GetLogsReq, opts ...grpc.CallOption) (*GetLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResp)
	err := c.cc.Invoke(ctx, Node_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetTxnStatus(ctx context.Context, in *GetTxnStatusReq, opts ...grpc.CallOption) (*GetTxnStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTxnStatusResp)
	err := c.cc.Invoke(ctx, Node_GetTxnStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetDB(ctx context.Context, in *GetDBReq, opts ...grpc.CallOption) (*GetDBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDBResp)
	err := c.cc.Invoke(ctx, Node_GetDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SetBalance(ctx context.Context, in *SetBalanceReq, opts ...grpc.CallOption) (*SetBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBalanceResp)
	err := c.cc.Invoke(ctx, Node_SetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResp)
	err := c.cc.Invoke(ctx, Node_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Checkpoint(ctx context.Context, in *CheckpointMsg, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, Node_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ResetDB(ctx context.Context, in *ResetDBReq, opts ...grpc.CallOption) (*ResetDBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetDBResp)
	err := c.cc.Invoke(ctx, Node_ResetDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	Request(context.Context, *TxnMessage) (*Reply, error)
	Request2PC(context.Context, *TxnMessage) (*Reply, error)
	Accept(context.Context, *AcceptMsg) (*AcceptedMsg, error)
	// 2PC-specific RPCs (separate from intra-shard Multi-Paxos)
	Prepare2PC(context.Context, *Prepare2PCReq) (*Prepare2PCResp, error)
	Accept2PC(context.Context, *Accept2PCMsg) (*Accept2PCResp, error)
	Commit2PC(context.Context, *Commit2PCMsg) (*Acknowledgement, error)
	Abort2PC(context.Context, *Abort2PCMsg) (*Acknowledgement, error)
	CommitPhase2PC(context.Context, *CommitPhase2PCReq) (*CommitPhase2PCResp, error)
	// rpc accepted(AcceptedReq) returns (Acknowledgement);
	Commit(context.Context, *CommitReq) (*Acknowledgement, error)
	// rpc reply(ReplyReq) returns (Acknowledgement);
	Prepare(context.Context, *PrepareReq) (*PromiseMsg, error)
	Heartbeat(context.Context, *HeartbeatMsg) (*Acknowledgement, error)
	NewView(context.Context, *NewViewRequest) (*NewViewReply, error)
	SetNodeState(context.Context, *NodeStateRequest) (*NodeStateReply, error)
	PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error)
	PrintDB(context.Context, *PrintDBRequest) (*PrintDBResponse, error)
	PrintStatus(context.Context, *PrintStatusRequest) (*PrintStatusResponse, error)
	PrintView(context.Context, *PrintViewRequest) (*PrintViewResponse, error)
	GetViewEntries(context.Context, *GetViewEntriesReq) (*GetViewEntriesResp, error)
	GetLogs(context.Context, *GetLogsReq) (*GetLogsResp, error)
	GetTxnStatus(context.Context, *GetTxnStatusReq) (*GetTxnStatusResp, error)
	GetDB(context.Context, *GetDBReq) (*GetDBResp, error)
	// Migration support: set explicit balances on a node (used during resharding).
	SetBalance(context.Context, *SetBalanceReq) (*SetBalanceResp, error)
	GetBalance(context.Context, *GetBalanceReq) (*GetBalanceResp, error)
	Checkpoint(context.Context, *CheckpointMsg) (*Acknowledgement, error)
	ResetDB(context.Context, *ResetDBReq) (*ResetDBResp, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Request(context.Context, *TxnMessage) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedNodeServer) Request2PC(context.Context, *TxnMessage) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request2PC not implemented")
}
func (UnimplementedNodeServer) Accept(context.Context, *AcceptMsg) (*AcceptedMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedNodeServer) Prepare2PC(context.Context, *Prepare2PCReq) (*Prepare2PCResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare2PC not implemented")
}
func (UnimplementedNodeServer) Accept2PC(context.Context, *Accept2PCMsg) (*Accept2PCResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept2PC not implemented")
}
func (UnimplementedNodeServer) Commit2PC(context.Context, *Commit2PCMsg) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit2PC not implemented")
}
func (UnimplementedNodeServer) Abort2PC(context.Context, *Abort2PCMsg) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort2PC not implemented")
}
func (UnimplementedNodeServer) CommitPhase2PC(context.Context, *CommitPhase2PCReq) (*CommitPhase2PCResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitPhase2PC not implemented")
}
func (UnimplementedNodeServer) Commit(context.Context, *CommitReq) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedNodeServer) Prepare(context.Context, *PrepareReq) (*PromiseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedNodeServer) Heartbeat(context.Context, *HeartbeatMsg) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeServer) NewView(context.Context, *NewViewRequest) (*NewViewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewView not implemented")
}
func (UnimplementedNodeServer) SetNodeState(context.Context, *NodeStateRequest) (*NodeStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNodeState not implemented")
}
func (UnimplementedNodeServer) PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedNodeServer) PrintDB(context.Context, *PrintDBRequest) (*PrintDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedNodeServer) PrintStatus(context.Context, *PrintStatusRequest) (*PrintStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintStatus not implemented")
}
func (UnimplementedNodeServer) PrintView(context.Context, *PrintViewRequest) (*PrintViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintView not implemented")
}
func (UnimplementedNodeServer) GetViewEntries(context.Context, *GetViewEntriesReq) (*GetViewEntriesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViewEntries not implemented")
}
func (UnimplementedNodeServer) GetLogs(context.Context, *GetLogsReq) (*GetLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedNodeServer) GetTxnStatus(context.Context, *GetTxnStatusReq) (*GetTxnStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxnStatus not implemented")
}
func (UnimplementedNodeServer) GetDB(context.Context, *GetDBReq) (*GetDBResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDB not implemented")
}
func (UnimplementedNodeServer) SetBalance(context.Context, *SetBalanceReq) (*SetBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBalance not implemented")
}
func (UnimplementedNodeServer) GetBalance(context.Context, *GetBalanceReq) (*GetBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedNodeServer) Checkpoint(context.Context, *CheckpointMsg) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedNodeServer) ResetDB(context.Context, *ResetDBReq) (*ResetDBResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDB not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call pancis, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Request(ctx, req.(*TxnMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Request2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Request2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Request2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Request2PC(ctx, req.(*TxnMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Accept(ctx, req.(*AcceptMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Prepare2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prepare2PCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Prepare2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Prepare2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Prepare2PC(ctx, req.(*Prepare2PCReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Accept2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accept2PCMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Accept2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Accept2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Accept2PC(ctx, req.(*Accept2PCMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Commit2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commit2PCMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Commit2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Commit2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Commit2PC(ctx, req.(*Commit2PCMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Abort2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Abort2PCMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Abort2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Abort2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Abort2PC(ctx, req.(*Abort2PCMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_CommitPhase2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPhase2PCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).CommitPhase2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_CommitPhase2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).CommitPhase2PC(ctx, req.(*CommitPhase2PCReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Commit(ctx, req.(*CommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Prepare(ctx, req.(*PrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Heartbeat(ctx, req.(*HeartbeatMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_NewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NewView(ctx, req.(*NewViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SetNodeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SetNodeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_SetNodeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SetNodeState(ctx, req.(*NodeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PrintLog(ctx, req.(*PrintLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PrintDB(ctx, req.(*PrintDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_PrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_PrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PrintStatus(ctx, req.(*PrintStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_PrintView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PrintView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_PrintView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PrintView(ctx, req.(*PrintViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetViewEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewEntriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetViewEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetViewEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetViewEntries(ctx, req.(*GetViewEntriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetLogs(ctx, req.(*GetLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetTxnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxnStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetTxnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetTxnStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetTxnStatus(ctx, req.(*GetTxnStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetDB(ctx, req.(*GetDBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_SetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SetBalance(ctx, req.(*SetBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetBalance(ctx, req.(*GetBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Checkpoint(ctx, req.(*CheckpointMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ResetDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetDBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ResetDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_ResetDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ResetDB(ctx, req.(*ResetDBReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request",
			Handler:    _Node_Request_Handler,
		},
		{
			MethodName: "Request2PC",
			Handler:    _Node_Request2PC_Handler,
		},
		{
			MethodName: "accept",
			Handler:    _Node_Accept_Handler,
		},
		{
			MethodName: "Prepare2PC",
			Handler:    _Node_Prepare2PC_Handler,
		},
		{
			MethodName: "Accept2PC",
			Handler:    _Node_Accept2PC_Handler,
		},
		{
			MethodName: "Commit2PC",
			Handler:    _Node_Commit2PC_Handler,
		},
		{
			MethodName: "Abort2PC",
			Handler:    _Node_Abort2PC_Handler,
		},
		{
			MethodName: "CommitPhase2PC",
			Handler:    _Node_CommitPhase2PC_Handler,
		},
		{
			MethodName: "commit",
			Handler:    _Node_Commit_Handler,
		},
		{
			MethodName: "prepare",
			Handler:    _Node_Prepare_Handler,
		},
		{
			MethodName: "heartbeat",
			Handler:    _Node_Heartbeat_Handler,
		},
		{
			MethodName: "NewView",
			Handler:    _Node_NewView_Handler,
		},
		{
			MethodName: "SetNodeState",
			Handler:    _Node_SetNodeState_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _Node_PrintLog_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _Node_PrintDB_Handler,
		},
		{
			MethodName: "PrintStatus",
			Handler:    _Node_PrintStatus_Handler,
		},
		{
			MethodName: "PrintView",
			Handler:    _Node_PrintView_Handler,
		},
		{
			MethodName: "GetViewEntries",
			Handler:    _Node_GetViewEntries_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Node_GetLogs_Handler,
		},
		{
			MethodName: "GetTxnStatus",
			Handler:    _Node_GetTxnStatus_Handler,
		},
		{
			MethodName: "GetDB",
			Handler:    _Node_GetDB_Handler,
		},
		{
			MethodName: "SetBalance",
			Handler:    _Node_SetBalance_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Node_GetBalance_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Node_Checkpoint_Handler,
		},
		{
			MethodName: "ResetDB",
			Handler:    _Node_ResetDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
